//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryURL { get; set; }
    }
}
